---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - 'recipe[tomcat_test::default]'
    attributes:
      tomcat_bin:
        install_java: true
