---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - 'recipe[apt]'
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - 'recipe[java]'
      - 'recipe[apache_tomcat::default]'
    attributes:
      apache_tomcat:
        install_java: true
        version: 7.0.56
      java:
        jdk_version: '7'
  - name: base
    run_list:
      - 'recipe[java]'
      - 'recipe[apache_tomcat::default]'
    attributes:
      apache_tomcat:
        install_java: true
        version: 7.0.56
        home: '/opt/tomcat'
        base: '/opt/tomcat'
      java:
        jdk_version: '7'
  - name: multi
    run_list:
      - recipe[java]
      - recipe[apache_tomcat::default]
    attributes:
      apache_tomcat:
        run_base_instance: false
        initial_heap_size: 256m
        instances:
          instance1:
            shutdown_port: 8005
            ajp_port: 8009
            http_port: 8080
            ssl_port: 8443
          instance2:
            ajp_port: 9009
            http_port: 9080
            ssl_port: 9443
      java:
        jdk_version: '7'
  - name: custom
    run_list:
      - 'recipe[java]'
      - 'recipe[apache_tomcat::default]'
    attributes:
      apache_tomcat:
        home: '/opt/tomcat7'
        base: '/var/tomcat'
        base_instance: 'tomcat-default'
        enable_manager: true
        webapps_mode: '0755'
        log_dir: '/var/log/tomcat7'
        logrotate_frequency: monthly
        logrotate_count: 12
        initial_heap_size: 256m
        max_heap_size: 512m
        shutdown_port: 9005
        ajp_port: 9009
        http_port: 9080
        http_additional:
          protocol: org.apache.coyote.http11.Http11NioProtocol
        ssl_port: 9443
        ssl_additional:
          protocol: org.apache.coyote.http11.Http11NioProtocol
        pool_enabled: true
        pool_additional:
          maxThreads: 250
          minSpareThreads: 25
        access_log_enabled: true
        engine_valves:
          org.apache.catalina.valves.RemoteIpValve:
            internalProxies: 127\.0\.0\.1
            protocolHeader: x-forwarded-proto
            portHeader: x-forwarded-port
        jmx_port: 9599
        jmx_monitor_password: mymonitorpw
        jmx_control_password: mycontrolpw
        tomcat_users:
          - id: joedirt
            password: mullet
            roles:
              -  manager-gui
      java:
        jdk_version: '7'
