AllCops:
  Include:
    - '**/Berksfile'
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

#inherit_from: .rubocop_todo.yml
