AllCops:
  Include:
    - '**/Berksfile'
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  Enabled: false

#inherit_from: .rubocop_todo.yml
