name             'apache_tomcat'
maintainer       'Brian Clark'
maintainer_email 'brian@clark.zone'
license          'apache2'
description      'Installs/Configures apache_tomcat'
long_description 'Installs/Configures apache_tomcat'
version          '0.2.0'

depends 'logrotate'
depends 'poise-service', '~> 1.0'
