name             'tomcat_bin'
maintainer       'Brian Clark'
maintainer_email 'brian@clark.zone'
license          'apache2'
description      'Installs/Configures tomcat_bin'
long_description 'Installs/Configures tomcat_bin'
version          '0.1.0'

depends 'ark'
depends 'java'
depends 'logrotate'
